export interface IndustryCategory {
  id: string | null;
  industryType: 'Ritel' | 'Restoran' | 'Layanan' | string;
  language: string;
  industryNameList: string[];
}

export const INDUSTRY_CATEGORIES: IndustryCategory[] = [
  {
    id: null,
    industryType: 'Ritel',
    language: 'id',
    industryNameList: [
      'Minimarket',
      'Toko Buah',
      'Toko Makanan Segar',
      'Pasar Tradisional',
      'Toko Kelontong',
      'Toko Pakaian',
      'Toko Tas',
      'Toko Sepatu',
      'Toko Perhiasan',
      'Toko Parfum',
      'Toko Kosmetik dan Perawatan Kulit',
      'Toko Buku',
      'Toko Alat Tulis',
      'Toko Furnitur',
      'Toko Elektronik',
      'Toko Peralatan Olahraga',
      'Toko Perlengkapan Hewan Peliharaan',
      'Toko Perkakas',
      'Apotek',
      'Toko Kacamata',
      'Toko Suku Cadang Mobil',
      'Toko Hadiah',
      'Lainnya',
    ],
  },
  {
    id: null,
    industryType: 'Restoran',
    language: 'id',
    industryNameList: [
      'Restoran Cepat Saji',
      'Restoran Teh Gaya Hong Kong',
      'Restoran Masakan Cina',
      'Restoran Masakan Barat',
      'Restoran Masakan Asia',
      'Kedai Kopi',
      'Kedai Teh dan Jus Buah',
      'Toko Kue dan Makanan Penutup',
      'Bar',
      'Restoran Hot Pot',
      'Restoran Prasmanan',
      'Food Truck',
      'Restoran Barbekyu/Panggang',
      'Kios di Pusat Kuliner',
      'Makanan Ringan & Cepat Saji',
      'Restoran untuk Pesta dan Acara',
      'Kantin/Makan Kelompok',
      'Lainnya',
    ],
  },
  {
    id: null,
    industryType: 'Layanan',
    language: 'id',
    industryNameList: [
      'Salon Kecantikan dan Rambut',
      'Salon Kecantikan Hewan Peliharaan',
      'Tempat Pijat',
      'Pusat Kebugaran',
      'Spa',
      'Titik Layanan Ekspedisi',
      'Bengkel Mobil',
      'Tempat Cuci Mobil',
      'Layanan Parkir',
      'Warnet',
      'Karaoke',
      'Tempat Reparasi Elektronik dan Jam Tangan',
      'Klinik Gigi',
      'Klinik Mata',
      'Layanan Medis Lainnya',
      'Hotel',
      'Lainnya',
    ],
  },
];
